replicaCount: 1
image:
  repository: flink
  pullPolicy: IfNotPresent
  tag: 1.13.0-scala_2.11-java8

flink:
  cluster:
    name: flink-native-cluster
    resources:
      jobManager:
        limits:
          cpu: 1250m
          memory: 3584Mi
        requests:
          cpu: 1000m
          memory: 2560Mi
      taskManager:
        limits:
          cpu: 1250m
          memory: 5120Mi
        requests:
          cpu: 1000m
          memory: 3072Mi
  configuration:
    kubernetes.cluster-id: test-ha-flink

    high-availability.cluster-id: /flink-native
    high-availability: org.apache.flink.kubernetes.highavailability.KubernetesHaServicesFactory
    high-availability.storageDir: s3a://<S3_BUCKET>/recovery

    s3.access-key: <ACCESS_KEY>
    s3.secret-key: <SECRET_KEY

    jobmanager.memory.process.size: 3072m
    taskmanager.memory.process.size: 4608m
    taskmanager.memory.jvm-metaspace.size: 384m
    taskmanager.memory.managed.fraction: 0.1

    taskmanager.numberOfTaskSlots: 1

    containerized.master.env.ENABLE_BUILT_IN_PLUGINS: flink-s3-fs-hadoop-1.13.0.jar
    containerized.taskmanager.env.ENABLE_BUILT_IN_PLUGINS: flink-s3-fs-hadoop-1.13.0.jar

