apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/tags: Environment={{ .Values.environmentName }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 8081}]'
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.privateDnsHostName }}
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: {{ .Values.flink.cluster.name }}-rest
              servicePort: 8081