apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-jobmanager-pod-template
data:
  jobmanager-pod-template.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: jobmanager-pod-template
    spec:
      containers:
        - name: flink-main-container
          resources:
            {{- toYaml .Values.flink.cluster.resources.jobManager | nindent 12 }}
      tolerations:
        - key: "serviceNode"
          operator: "Equal"
          value: "flink"
          effect: "NoSchedule"
